# docker-compose.yml
version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:8080"
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:8080"
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}

  nginx:
    image: nginx:alpine
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/mginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
